# -*- coding: utf-8 -*-
"""Cross_market.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vxzXW85g3D57tVWSeZW8mnhYww3CE_wf
"""

!pip install mysql-connector-python yfinance requests pandas

import requests
import pandas as pd

all_data = []

for page in range(1, 3):  # adjust pages if needed
    url = "https://api.coingecko.com/api/v3/coins/markets"
    params = {
        "vs_currency": "inr",
        "order": "market_cap_desc",
        "per_page": 250,
        "page": page,
        "sparkline": False
    }

    response = requests.get(url, params=params)
    data = response.json()
    all_data.extend(data)

df_crypto = pd.DataFrame(all_data)

df_crypto = df_crypto[
    [
        "id","symbol","name","current_price","market_cap",
        "market_cap_rank","total_volume","circulating_supply",
        "total_supply","ath","atl","last_updated"
    ]
]

df_crypto["date"] = pd.to_datetime(df_crypto["last_updated"]).dt.date
df_crypto.drop(columns=["last_updated"], inplace=True)

df_crypto.head()

import mysql.connector

conn = mysql.connector.connect(
    host="gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
    port=4000,
    user="4Z5hFB6ww8VYsR9.root",
    password="FzHpvkTZ17zScCXM",
    database="crypto_project"
)

cursor = conn.cursor()
print("Connected to MySQL successfully")

!pip install streamlit

for _, row in df_crypto.iterrows():
    row_data = row.copy()
    row_data['circulating_supply'] = round(row_data['circulating_supply'])
    row_data['total_supply'] = round(row_data['total_supply'])

    cursor.execute("""
        insert ignore into cryptocurrencies
        values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row_data))

conn.commit()
print("Cryptocurrency metadata inserted")

top3 = df_crypto.sort_values("market_cap_rank").head(3)["id"].tolist()
print(top3)

historical_data = []

for coin in top3:
    url = f"https://api.coingecko.com/api/v3/coins/{coin}/market_chart"
    params = {"vs_currency": "inr", "days": 365}

    response = requests.get(url, params=params)

    if response.status_code == 200:
        try:
            data = response.json()["prices"]
        except requests.exceptions.JSONDecodeError:
            print(f"Error decoding JSON for {coin}. Response content: {response.text}")
            continue # Skip to the next coin if JSON is malformed
    else:
        print(f"API request failed for {coin} with status code {response.status_code}. Response content: {response.text}")
        continue # Skip to the next coin if request failed

    for item in data:
        date = pd.to_datetime(item[0], unit="ms").date()
        price = item[1]
        historical_data.append([coin, date, price])

df_prices = pd.DataFrame(historical_data, columns=["coin_id","date","price_usd"])
df_prices.head()

for _, row in df_prices.iterrows():
    cursor.execute("""
        insert into crypto_prices
        values (%s,%s,%s)
    """, tuple(row))

conn.commit()
print("Crypto historical prices inserted")

oil_url = "https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv"
df_oil = pd.read_csv(oil_url)

df_oil["Date"] = pd.to_datetime(df_oil["Date"])
df_oil = df_oil[(df_oil["Date"] >= "2020-01-01") & (df_oil["Date"] <= "2026-01-01")]

df_oil = df_oil.rename(columns={"Date":"date","Price":"price_usd"})
df_oil.head()

for _, row in df_oil.iterrows():
    cursor.execute("""
        INSERT INTO oil_prices
        VALUES (%s,%s)
    """, tuple(row))

conn.commit()
print("Oil data inserted")

import yfinance as yf
import pandas as pd

tickers = ["^GSPC","^IXIC","^NSEI"]

stock_data = []

for ticker in tickers:
    data = yf.download(ticker, start="2020-01-01", end="2025-09-01")
    data.reset_index(inplace=True)

    data['Date'] = pd.to_datetime(data['Date']).dt.date

    for _, row in data.iterrows():
       stock_data.append([
            row["Date"].item(), # Apply .item() to 'Date' as well
            row["Open"].item(),
            row["High"].item(),
            row["Low"].item(),
            row["Close"].item(),
            row["Volume"].item(),
            ticker
        ])

df_stocks = pd.DataFrame(
    stock_data,
    columns=["date","open","high","low","close","volume","ticker"]
)

df_stocks.head()

insert_query = """
    insert into stock_prices
    (date, open, high, low, close, volume, ticker)
    values (%s,%s,%s,%s,%s,%s,%s)
"""

data_to_insert = [tuple(row) for row in df_stocks.values]

cursor.executemany(insert_query, data_to_insert)

conn.commit()

print("Stock data inserted successfully 🚀")

for _, row in df_stocks.iterrows():
    cursor.execute("""
        insert into stock_prices
        values (%s,%s,%s,%s,%s,%s,%s)
    """, tuple(row))

conn.commit()
print("Stock data inserted")

tables = ["cryptocurrencies", "crypto_prices", "oil_prices", "stock_prices"]

for table in tables:
    cursor.execute(f"select count(*) from {table}")
    count = cursor.fetchone()[0]
    print(f"{table} → {count} records")

cursor.execute("""
select name, market_cap
from cryptocurrencies
order by market_cap desc;
""")

for row in cursor.fetchall():
    print(row)

cursor.execute("""
select avg(current_price)
from cryptocurrencies;
""")

print("Average crypto price:", cursor.fetchone()[0])

cursor.execute("""
select ticker, max(close)
from stock_prices
group by ticker;
""")

for row in cursor.fetchall():
    print(row)

cursor.execute("""
select avg(price_usd)
from oil_prices;
""")

print("Average oil price:", cursor.fetchone()[0])

cursor.execute("""
select
    cp.date,
    avg(cp.price_usd) as avg_crypto_price,
    op.price_usd as oil_price
from crypto_prices cp
join oil_prices op
on cp.date = op.date
group by cp.date;
""")

for row in cursor.fetchall():
    print(row)

query = """
select
    cp.date,
    avg(cp.price_usd) as avg_crypto,
    op.price_usd as oil_price
from crypto_prices cp
join oil_prices op
on cp.date = op.date
group by cp.date
"""

df_analysis = pd.read_sql(query, conn)


df_analysis_numeric = df_analysis.drop(columns=['date'])
print(df_analysis_numeric.corr())

cursor.execute("""
select name, symbol, market_cap
from cryptocurrencies
order by market_cap desc;
""")

for row in cursor.fetchall():
    print(row)

cursor.execute("""
select
    max(current_price) as highest_price,
    min(current_price) as lowest_price
from cryptocurrencies;
""")

print(cursor.fetchone())

cursor.execute("""
select name, total_volume
from cryptocurrencies
order by total_volume desc;
""")

for row in cursor.fetchall():
    print(row)

cursor.execute("""
select avg(price_usd)
from oil_prices;
""")

print("Average Oil Price:", cursor.fetchone()[0])

cursor.execute("""
select
    max(price_usd),
    min(price_usd)
from oil_prices;
""")

print(cursor.fetchone())

cursor.execute("""
select ticker, MAX(close)
from stock_prices
group BY ticker;
""")

for row in cursor.fetchall():
    print(row)

cursor.execute("""
select ticker, avg(volume)
from stock_prices
group by ticker;
""")

for row in cursor.fetchall():
    print(row)

query = """
select
    cp.date,
    avg(cp.price_usd) as avg_crypto_price,
    op.price_usd as oil_price
from crypto_prices cp
join oil_prices op
on cp.date = op.date
group by cp.date
order by cp.date;
"""

df_cross = pd.read_sql(query, conn)
df_cross.head()

df_cross_numeric = df_cross.drop(columns=['date'])
print(df_cross_numeric.corr())

query = """
select ticker,
       (max(close) - min(close)) / min(close) * 100 as return_percentage
from stock_prices
group by ticker;
"""

cursor.execute(query)

for row in cursor.fetchall():
    print(row)

pip install streamlit mysql-connector-python pandas matplotlib seaborn

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import mysql.connector

st.set_page_config(page_title="Cross Market Dashboard", layout="wide")

st.title("📊 Cross Market Analysis Dashboard")


conn = mysql.connector.connect(
    host="gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
    port=4000,
    user="4Z5hFB6ww8VYsR9.root",
    password="FzHpvkTZ17zScCXM",
    database="crypto_project"
)

menu = st.sidebar.selectbox(
    "Select Analysis",
    ["Crypto Market", "Oil Market", "Stock Market", "Cross Market"]
)


if menu == "Crypto Market":

    query = "select name, market_cap from cryptocurrencies order by market_cap desc"
    df = pd.read_sql(query, conn)

    st.subheader("Top 10 Cryptocurrencies by Market Cap")

    fig, ax = plt.subplots()
    ax.bar(df["name"], df["market_cap"])
    plt.xticks(rotation=45)
    st.pyplot(fig)


elif menu == "Oil Market":

    query = "select date, price_usd from oil_prices"
    df = pd.read_sql(query, conn)

    st.subheader("Oil Price Trend")

    fig, ax = plt.subplots()
    ax.plot(df["date"], df["price_usd"])
    st.pyplot(fig)


elif menu == "Stock Market":

    query = "select date, close, ticker from stock_prices"
    df = pd.read_sql(query, conn)

    st.subheader("Stock Market Trend")

    ticker = st.selectbox("Select Ticker", df["ticker"].unique())
    df_filtered = df[df["ticker"] == ticker]

    fig, ax = plt.subplots()
    ax.plot(df_filtered["date"], df_filtered["close"])
    st.pyplot(fig)


elif menu == "Cross Market":

    query = """
    select
        cp.date,
        avg(cp.price_usd) as avg_crypto,
        op.price_usd as oil_price
    from crypto_prices cp
    join oil_prices op
    on cp.date = op.date
    group by cp.date
    """

    df = pd.read_sql(query, conn)

    st.subheader("Crypto vs Oil Comparison")

    fig, ax = plt.subplots()
    ax.plot(df["date"], df["avg_crypto"], label="Crypto Avg")
    ax.plot(df["date"], df["oil_price"], label="Oil Price")
    ax.legend()
    st.pyplot(fig)

queries = {
    "Top 3 Crypto": "select ...",
    "Oil Highest 5Y": "select ..."
}

selected_query = st.selectbox("Choose Query", list(queries.keys()))

if st.button("Run Query"):
    df = pd.read_sql(queries[selected_query], conn)
    st.dataframe(df)

queries = {


    "Top 3 Cryptos by Market Cap":
    """
    select name, market_cap
    from cryptocurrencies
    order by market_cap DESC
    limit 3
    """,

    "Coins with Circulating Supply > 90%":
    """
    select name, circulating_supply, total_supply
    from cryptocurrencies
    where circulating_supply >= 0.9 * total_supply
    """,

    "Coins Within 10% of ATH":
    """
    select name, current_price, ath
    from cryptocurrencies
    where current_price >= 0.9 * ath
    """,

    "Average Market Cap Rank (Volume > $1B)":
    """
    select avg(market_cap_rank) as avg_rank
    from cryptocurrencies
    where total_volume > 1000000000
    """,

    "Most Recently Updated Coin":
    """
    select *
    from cryptocurrencies
    order by date desc
    limit 1
    """,


    "Bitcoin Highest Price (1 Year)":
    """
    select max(price_usd) AS highest_price
    from crypto_prices
    where coin_id = 'bitcoin'
    and date >= curdate() - interval 365 day
    """,

    "Ethereum Average Price (1 Year)":
    """
    select avg(price_usd) as eth_avg_price
    from crypto_prices
    where coin_id = 'ethereum'
    and date >= curdate() - interval 365 day
    """,

    "Coin with Highest Avg Price (1 Year)":
    """
    select coin_id, avg(price_usd) as avg_price
    from crypto_prices
    where date >= curdate() - interval 365 day
    group by coin_id
    order by avg_price desc
    limit 1
    """,


    "Highest Oil Price (5 Years)":
    """
    select max(price_usd) as highest_oil
    from oil_prices
    where date >= curdate() - interval 5 year
    """,

    "Average Oil Price Per Year":
    """
    select year(date) as year, avg(price_usd) as avg_price
    from oil_prices
    group by year(date)
    order by year
    """,

    "Lowest Oil Price (10 Years)":
    """
    select min(price_usd) as lowest_price
    from oil_prices
    where date >= curdate() - interval 10 year
    """,

    "Oil Volatility Per Year (Max-Min)":
    """
    select year(date) as year,
           max(price_usd) - min(price_usd) as volatility
    from oil_prices
    group by year(date)
    order by year
    """,


    "Highest NASDAQ Close":
    """
    select max(close) as highest_nasdaq
    from stock_prices
    where ticker = '^IXIC'
    """,

    "Top 5 S&P 500 High-Low Spread Days":
    """
    select date, high - low as price_difference
    from stock_prices
    where ticker = '^GSPC'
    order by price_difference desc
    limit 5
    """,

    "Monthly Average Closing Price (All Tickers)":
    """
    selewct ticker,
           year(date) as year,
           month(date) as month,
           avg(close) as avg_close
    from stock_prices
    group by ticker, year(date), month(date)
    order by ticker, year, month
    """,

    "Average NSEI Volume (2024)":
    """
    select avg(volume) as avg_volume_2024
    from stock_prices
    where ticker = '^NSEI'
    and year(date) = 2024
    """,


    "Bitcoin vs Oil Avg Price (2025)":
    """
    select
        avg(c.price_usd) as bitcoin_avg,
        avg(o.price_usd) as oil_avg
    from crypto_prices c
    join oil_prices o on c.date = o.date
    where c.coin_id = 'bitcoin'
    and year(c.date) = 2025
    """,

    "Bitcoin vs S&P 500 Daily Comparison (2025)":
    """
    select c.date,
           c.price_usd AS bitcoin_price,
           s.close AS sp500_close
    from crypto_prices c
    join stock_prices s on c.date = s.date
    where c.coin_id = 'bitcoin'
    and s.ticker = '^GSPC'
    and year(c.date) = 2025
    """,

    "Ethereum vs NASDAQ (2025)":
    """
    select c.date,
           c.price_usd AS ethereum_price,
           s.close AS nasdaq_close
    from crypto_prices c
    join stock_prices s on c.date = s.date
    where c.coin_id = 'ethereum'
    and s.ticker = '^IXIC'
    and year(c.date) = 2025
    """,

    "Multi-Market Daily Comparison":
    """
    select c.date,
           c.price_usd AS bitcoin_price,
           o.price_usd AS oil_price,
           s.close AS sp500_close
    from crypto_prices c
    join oil_prices o on c.date = o.date
    join stock_prices s on c.date = s.date and s.ticker = '^GSPC'
    where c.coin_id = 'bitcoin'
    order by c.date
    """
}



























